---
title: "Maximum LogLikelihood Analysis (Re)"
author: "Cher Yang"
date: "52/13/2022"
output:
  html_document:
    code_folding: hide
    theme: yeti
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
  word_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, message = FALSE, tidy = TRUE)
```

```{r}
# data wrangling
library(tidyverse, warn.conflicts = FALSE, quietly = TRUE)
library(tidyr, warn.conflicts = FALSE, quietly = TRUE)
library(dplyr, warn.conflicts = FALSE, quietly = TRUE)
library(ggplot2)
library(ggpubr)
library(sjPlot)
library(kableExtra)
library(xtable)
library(plotly)
library(ggthemes)
library(ggbeeswarm)

# linear model
library(lme4)
library(afex) # mixed effect model
library(optimx)
library(permuco)
library(remotes)
library(permutes)
library(coin)

rm(list=ls())

set.seed(0)
```

## Load Data

Load maxLL data

```{r} 
# save plot or not
SAVE_PLOT <- FALSE

# load subject agg data
SUB_PATH <- "../data/subject_data/*/aggregate/*.csv"

# join subject and maxLL data
d <- do.call('rbind', lapply(Sys.glob(SUB_PATH), function(i){read.csv(i)})) %>%
  left_join(read.csv("../data/actr_maxLL.csv"), by = "HCPID") %>% 
  mutate(weights = abs(LL.diff)) %>%
  mutate(Group = ifelse(BestModel == "model1", "Declarative", "Procedural"), 
         `Trial Type` = factor(ifelse(TrialType=="Reward", "Win", ifelse(TrialType=="Punishment", "Loss", TrialType)),  levels = c("Win", "Loss", "Neutral")),
         `Block Type` = factor(ifelse(BlockType=="MostlyReward", "Mostly Win", "Mostly Losses"), levels = c("Mostly Win", "Mostly Losses"))) %>% 
  select(-c(X.x, X.y))

```


## Visualize Best-Fit Groups

```{r}
d %>% select(HCPID, BestModel) %>% unique() %>% count(BestModel) %>%
  mutate(BestModel = ifelse(BestModel == "model1", "Declarative", "Procedural")) %>%
  ggbarplot(x = "BestModel", y="n", label = T, lab.pos = "in", lab.size = 10, lab.col = "white", 
            title = "Subjects' Decision-Making Strategies Identified by ACT-R Models", 
            xlab="Model",  ylab = "Number of Subjects",
            color = c("red3", "steelblue"), fill=c("red3", "steelblue")) +
  theme_pander(base_size = 25)

if (SAVE_PLOT) {
  ggsave("./maxloglikelihood_analysis_files/figure-html/figure1A.jpeg", units="in", width=15, height=4, dpi=300)
}
```


```{r}
d %>% 
  ggplot(aes(x = `Trial Type`, y = ResponseSwitch, group=Group, color=Group)) +
  facet_grid(~ `Block Type`, labeller = label_both) +
  labs(y="Probability of Switching", x="Feedback") +
  scale_color_brewer(palette = "Set2") +
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange", show.legend = T, size=2,
               position = position_dodge(width = .5)) +
  stat_summary(fun.data = "mean_cl_boot", geom = "line", , show.legend = F, size=1.5,
               position =  position_dodge(width = .5)) +
  scale_color_manual(values = c("red3", "steelblue")) + 
  theme_pander(base_size = 25, lp = "bottom")

if (SAVE_PLOT) {
  ggsave("./maxloglikelihood_analysis_files/figure-html/figure1B.jpeg", units="in", width=15, height=4, dpi=300)
}
```

```{r eval=FALSE}

d <- read.csv("../data/max_loglikelihood.csv", sep = ",") %>%
  select(HCPID, best_model, maxLL_diff, 
         Punishment_MostlyPunishment.subj, 
         Reward_MostlyPunishment.subj, 
         Reward_MostlyReward.subj, 
         Punishment_MostlyReward.subj) %>%
  pivot_longer(Punishment_MostlyPunishment.subj:Punishment_MostlyReward.subj,
               names_to = "Condition",
               values_to = "Pswitch") %>% 
  mutate(
    block_type = case_when(
      Condition == "Reward_MostlyPunishment.subj" ~ "Loss",
      Condition == "Punishment_MostlyPunishment.subj" ~ "Loss",
      Condition == "Reward_MostlyReward.subj" ~ "Reward",
      Condition == "Punishment_MostlyReward.subj" ~ "Reward",
      TRUE ~ "NA"), 
    trial_type = case_when(
      Condition == "Punishment_MostlyReward.subj" ~ "Loss",
      Condition == "Punishment_MostlyPunishment.subj" ~ "Loss",
      Condition == "Reward_MostlyReward.subj" ~ "Reward",
      Condition == "Reward_MostlyPunishment.subj" ~ "Reward",
      TRUE ~ "NA"), 
    ) 

#d.trial = d %>% 
#  group_by(HCPID, trial_type, best_model) %>%
#  summarise(Pswitch = mean(Pswitch))
```

## Stat Analysis
### Mixed Effect Model 

We could fit data using `glmer`

- Random effects: `HCPID`
- Fixed effects: `BestModel`, `TrialType`, `BlockType`
- id: `HCPID`
- binomial distribution

Fitting data to mixed effect linear model, `BestModel` label is significant 
 

````{r}
m1 <- glmer(data = d, formula = ResponseSwitch ~ BestModel + BlockType * TrialType + (1| HCPID), family = binomial)

#xtable(nice(m1))
summary(m1)
```

```{r eval=FALSE}

#try apex library
m1 <- mixed(data = d, formula = ResponseSwitch ~ BestModel + BlockType * TrialType + (1| HCPID),  
            method = "LRT", 
            all_fit = TRUE, 
            family = binomial)
nice(m1)
summary(m1)
```
 
